function [ID,DYTime,DYTime1,DX,DY] = import_trackball(filename, startRow, endRow)
%IMPORT_TRACKBALL Import numeric data from a text file as column vectors.
%   [ID,DYTIME,DYTIME1,DX,DY] = IMPORT_TRACKBALL(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [ID,DYTIME,DYTIME1,DX,DY] = IMPORT_TRACKBALL(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [ID,DYTime,DYTime1,DX,DY] = import_trackball('trackball_20131013_1024.txt',5,
%   215029);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/11/26 09:03:31

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ID = dataArray{:, 1};
DYTime = dataArray{:, 2};
DYTime1 = dataArray{:, 3};
DX = dataArray{:, 4};
DY = dataArray{:, 5};



